apiVersion: apps/v1
kind: Deployment
metadata:
  name: theraswitchrx-minimal
  labels:
    app: theraswitchrx-minimal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theraswitchrx-minimal
  template:
    metadata:
      labels:
        app: theraswitchrx-minimal
    spec:
      containers:
      - name: theraswitchrx-minimal
        image: theraswitchrx:minimal
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: DISABLE_PIPELINE
          value: "false"
        - name: GROQ_API_KEY
          value: "gsk_YOUR_GROQ_API_KEY_HERE"

        resources:
          requests:
            memory: "1Gi"
            cpu: "200m"
          limits:
            memory: "3Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 5000
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: theraswitchrx-minimal-service
  labels:
    app: theraswitchrx-minimal
spec:
  type: LoadBalancer
  selector:
    app: theraswitchrx-minimal
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http